name: Develop Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Static Analysis
        run: |
          pip install ruff
          ruff check . || true
      
      - name: Dependency Check
        run: |
          pip install pip-audit
          pip-audit || true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        working-directory: ./saleor-api
        run: docker build -t saleor-api:develop .
      
      - name: Health Check
        run: |
          docker run -d -p 8000:8000 saleor-api:develop
          sleep 10
          curl -f http://localhost:8000/health || curl -f http://localhost:8000/graphql

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'saleor-api:develop'
          format: 'table'
          exit-code: '0'

      - name: Push to DockerHub
        run: |
          docker tag saleor-api:develop ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop
          docker push ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop
