name: Develop Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Static Analysis
        working-directory: ./saleor-api
        run: |
          pip install ruff
          ruff check . || true
      
      - name: Dependency Check
        working-directory: ./saleor-api
        run: |
          pip install pip-audit
          pip-audit || true

  build-and-test:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Images
        run: |
          cd saleor-api && docker build -t saleor-api:develop .
          cd ../saleor-dashboard && docker build -t saleor-dashboard:develop .

      - name: Create test environment
        run: |
          docker network create saleor-network
          docker run -d --name postgres \
            --network saleor-network \
            -e POSTGRES_DB=saleor \
            -e POSTGRES_USER=saleor \
            -e POSTGRES_PASSWORD=saleor \
            postgres:13
          docker run -d --name redis \
            --network saleor-network \
            redis:6.2

      - name: Start Services with Docker Compose
        run: |
          docker compose up -d
          echo "Currently running containers:"
          docker ps -a
          sleep 60

      - name: API Health Check
        run: |
          echo "Testing API health..."
          curl -v http://localhost:8000/health

      - name: Test Dashboard
        run: |
          echo "Waiting for the dashboard to be ready..."
         
          for i in {1..10}; do
            if curl -s http://localhost:9000; then
              echo "Dashboard is up!"
              exit 0
            fi
            echo "Retrying in 10 seconds..."
            sleep 10
          done

          echo "Dashboard failed to start."
          docker logs dashboard
          exit 1

      - name: API Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'saleor-api:develop'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Dashboard Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'saleor-dashboard:develop'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Push to DockerHub
        if: success()
        run: |
          docker tag saleor-api:develop ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop
          docker push ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop
          docker tag saleor-dashboard:develop ${{ secrets.DOCKER_USERNAME }}/saleor-dashboard:develop
          docker push ${{ secrets.DOCKER_USERNAME }}/saleor-dashboard:develop

      - name: Cleanup
        if: always()
        run: |
          docker compose down
          docker rm -f postgres redis || true
          docker network rm saleor-network || true

