name: Develop Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Static Analysis
        run: |
          pip install ruff
          ruff check . || true
      
      - name: Dependency Check
        run: |
          pip install pip-audit
          pip-audit || true

  build:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create test environment
        run: |
          docker network create saleor-network
          docker run -d --name postgres \
            --network saleor-network \
            -e POSTGRES_DB=saleor \
            -e POSTGRES_USER=saleor \
            -e POSTGRES_PASSWORD=saleor \
            postgres:13
          docker run -d --name redis \
            --network saleor-network \
            redis:6.2

      - name: Build and run API
        working-directory: ./saleor-api
        run: |
          docker build -t saleor-api:develop .
          docker run -d --name saleor-api \
            --network saleor-network \
            -e DEBUG=True \
            -e DATABASE_URL=postgres://saleor:saleor@postgres:5432/saleor \
            -e REDIS_URL=redis://redis:6379/0 \
            -e SECRET_KEY=testing123 \
            -p 8000:8000 \
            saleor-api:develop

      - name: Wait and check health
        run: |
          echo "Waiting for services to start..."
          sleep 45
          echo "Container logs:"
          docker logs saleor-api
          echo "Testing API health..."
          curl -v http://localhost:8000/health

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'saleor-api:develop'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Push to DockerHub
        if: success()
        run: |
          docker tag saleor-api:develop ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop
          docker push ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop

      - name: Cleanup
        if: always()
        run: |
          docker rm -f saleor-api postgres redis || true
          docker network rm saleor-network || true
