name: Develop Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: API Static Analysis
        working-directory: ./saleor-api
        run: |
          pip install ruff
          ruff check .
      
      - name: API Dependency Check
        working-directory: ./saleor-api
        run: |
          pip install pip-audit
          pip-audit || true

      - name: Dashboard Static Analysis
        working-directory: ./saleor-dashboard
        run: |
          pip install ruff
          ruff check .
      
      - name: Dashboard Dependency Check
        working-directory: ./saleor-dashboard
        run: |
          pip install pip-audit
          pip-audit || true

  build-and-test:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API Image
        run: |
          cd saleor-api && docker build -t saleor-api:develop .
      
      - name: Build Dashboard Image
        run: |
          cd saleor-dashboard && docker build -t saleor-dashboard:develop .
      
      - name: Start API and Dependencies
        run: |
          docker network create saleor-network
          docker run -d --name postgres --network saleor-network -e POSTGRES_DB=saleor -e POSTGRES_USER=saleor -e POSTGRES_PASSWORD=saleor postgres:13
          docker run -d --name redis --network saleor-network redis:6.2
          docker run -d --name saleor-api --network saleor-network -p 8000:8000 saleor-api:develop
          sleep 30  # Wait for API to start
          echo "Currently running containers:" && docker ps -a
      
      - name: API Health Check
        run: |
          echo "Testing API health..."
          curl -v http://localhost:8000/health
      
      - name: Start Dashboard
        run: |
          docker run -d --name saleor-dashboard --network saleor-network -p 9000:9000 saleor-dashboard:develop
      
      - name: API Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'saleor-api:develop'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
      
      - name: Dashboard Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'saleor-dashboard:develop'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
      
      - name: Push to DockerHub
        if: success()
        run: |
          docker tag saleor-api:develop ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop
          docker push ${{ secrets.DOCKER_USERNAME }}/saleor-api:develop
          docker tag saleor-dashboard:develop ${{ secrets.DOCKER_USERNAME }}/saleor-dashboard:develop
          docker push ${{ secrets.DOCKER_USERNAME }}/saleor-dashboard:develop
      
      - name: Cleanup
        if: always()
        run: |
          docker rm -f saleor-api saleor-dashboard postgres redis || true
          docker network rm saleor-network || true
