name: Staging Pipeline

on:
  push:
    branches: [ staging ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Compose Validation
        run: |
          docker-compose up -d
          docker-compose ps | grep -q "healthy"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push
        run: |
          docker build -t saleor-api:staging .
          docker tag saleor-api:staging ${{ secrets.DOCKER_USERNAME }}/saleor-api:staging
          docker push ${{ secrets.DOCKER_USERNAME }}/saleor-api:staging
